# Generated by Django 3.1.2 on 2020-10-12 11:35

from django.db import migrations, models
import django.db.models.deletion
import patterns.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteswap', models.CharField(max_length=200)),
                ('prop_type', models.CharField(choices=[(patterns.models.PropType['BALLS'], 'balls'), (patterns.models.PropType['CLUBS'], 'clubs'), (patterns.models.PropType['RINGS'], 'rings')], max_length=5)),
                ('modifiers', models.JSONField(choices=[(patterns.models.Modifier['MILLS_MESS'], 0), (patterns.models.Modifier['WHILE_BALANCING_A_CLUB_ON_THE_FACE'], 1)], default=list)),
                ('body_throw', models.JSONField(choices=[(patterns.models.BodyThrow['BEHIND_THE_BACK'], 'behind the back'), (patterns.models.BodyThrow['BEHIND_THE_SHOULDER'], 'behind the shoulder'), (patterns.models.BodyThrow['UNDER_THE_ARM'], 'under the arm'), (patterns.models.BodyThrow['UNDER_THE_LEG'], 'under the leg')], default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_objects', models.PositiveIntegerField(default=20)),
                ('max_height_minus_min_height', models.IntegerField(default=20)),
                ('body_throw_difficulty', models.IntegerField(default=100)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern')),
            ],
        ),
    ]
