# Generated by Django 3.1.2 on 2020-10-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteswap', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_objects', models.PositiveIntegerField(default=20)),
                ('max_height_minus_min_height', models.IntegerField(default=20)),
                ('body_throw_difficulty', models.IntegerField(default=100)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern')),
            ],
        ),
    ]
