# Generated by Django 3.1.2 on 2020-10-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteswap', models.CharField(max_length=200)),
                ('prop_type', models.CharField(choices=[('ball', 'Ball'), ('club', 'Club'), ('ring', 'Ring')], max_length=5)),
                ('modifiers', models.JSONField(choices=[('MILLS_MESS', "Mills' mess"), ('WHILE_BALANCING_A_CLUB_ON_THE_FACE', 'while balancing a club on the face')], default=list)),
                ('body_throw', models.JSONField(choices=[('BEHIND_THE_BACK', 'behind the back'), ('BEHIND_THE_SHOULDER', 'behind the shoulder'), ('UNDER_THE_ARM', 'under the arm'), ('UNDER_THE_LEG', 'under the leg')], default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_objects', models.PositiveIntegerField(default=20, verbose_name='number of objects')),
                ('max_height_minus_min_height', models.IntegerField(default=20, verbose_name='maximum height - minimum height')),
                ('body_throw_difficulty', models.IntegerField(default=100)),
                ('pattern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern')),
            ],
            options={
                'verbose_name_plural': 'Difficulty',
            },
        ),
    ]
