# Generated by Django 3.1.2 on 2020-10-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyThrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw_moment', models.CharField(max_length=1)),
                ('throw_type', models.CharField(choices=[('behind the back', 'behind the back'), ('behind the shoulder', 'behind the shoulder'), ('under the arm', 'under the arm'), ('under the leg', 'under the leg')], max_length=20)),
                ('catch_or_throw', models.CharField(choices=[('catch', 'catch'), ('throw', 'throw'), ('catch and throw', 'catch and throw')], max_length=15)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern')),
            ],
        ),
    ]
