# Generated by Django 3.1.2 on 2020-10-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_bodythrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodythrow',
            name='catch_or_throw',
            field=models.CharField(choices=[('caught', 'catch'), ('thrown', 'throw'), ('caught and thrown', 'catch and throw')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bodythrow',
            name='throw_type',
            field=models.CharField(choices=[('behind the back', 'behind the back'), ('behind the neck', 'behind the neck'), ('behind the shoulder', 'behind the shoulder'), ('under the arm', 'under the arm'), ('under the leg', 'under the leg')], max_length=20),
        ),
    ]
