# Generated by Django 3.1.2 on 2020-11-02 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patterns', '0002_auto_20201102_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_user1', to=settings.AUTH_USER_MODEL),
        ),
    ]
