# Generated by Django 3.1.2 on 2020-10-26 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_auto_20201026_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='number of jugglers',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
