# Generated by Django 3.1.2 on 2020-10-26 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_pattern_number of jugglers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='user',
            new_name='user_or_team',
        ),
        migrations.AddField(
            model_name='pattern',
            name='body_throw_difficulty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Body throw difficulty (0: no body throws, 100: maximum difficulty)'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='max_height_minus_min_height',
            field=models.IntegerField(default=0, editable=False, verbose_name='maximum height - minimum height'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='n_objects',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='number of objects'),
        ),
        migrations.DeleteModel(
            name='Difficulty',
        ),
    ]
