# Generated by Django 3.1.2 on 2020-10-15 13:11

from django.db import migrations, models
import patterns.models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_auto_20201014_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='max_height_minus_min_height',
            field=models.IntegerField(editable=False, verbose_name='maximum height - minimum height'),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='n_objects',
            field=models.PositiveIntegerField(editable=False, verbose_name='number of objects'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='siteswap',
            field=models.CharField(max_length=200, validators=[patterns.models.validate_siteswap_characters, patterns.models.validate_siteswap_integer_average]),
        ),
    ]
