# Generated by Django 3.1.2 on 2020-11-04 10:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patterns', '0004_auto_20201103_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('column', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
