# Generated by Django 3.1.2 on 2020-10-26 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_auto_20201026_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='number of jugglers',
        ),
        migrations.AddField(
            model_name='pattern',
            name='n_jugglers',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of jugglers'),
        ),
    ]
