# Generated by Django 3.1.2 on 2020-11-04 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0005_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='column',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
