# Generated by Django 3.1.2 on 2020-10-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0005_auto_20201015_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='body_throw_difficulty',
            field=models.IntegerField(default=0, verbose_name='Body throw difficulty (0: no body throws, 100: maximum difficulty)'),
        ),
    ]
