# Generated by Django 3.1.2 on 2020-11-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0006_auto_20201104_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='column',
        ),
    ]
