# Generated by Django 3.1.2 on 2020-10-26 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patterns', '0006_auto_20201016_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='body_throw_difficulty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Body throw difficulty (0: no body throws, 100: maximum difficulty)'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_catches', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.pattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
